### PR TITLE
Added missing content in the docs && fixed i18n

### PR DESCRIPTION
**Pull request by celaraze**
1, fixed some missing links.
2, added missing content.
3, the docs directory structure has been modified to follow i18n specification.

### CODE REVIEW

**Review by 4ud5quad1009 — APPROVED** [review]

**Comment by celaraze** [comment]
fix conflicts.

**Comment by zhengzangw** [comment]
Thank you for your contribution. Your suggestion is valuable. Let me resolve the conflicts for you.

**Review by zhengzangw — APPROVED** [review]
I will make a new pull request to resolve the conflict.

**Comment by zhengzangw** [comment]
Moved to https://github.com/hpcaitech/Open-Sora/pull/197

**Comment by celaraze** [comment]
> I will make a new pull request to resolve the conflict.

gotcha, thank you.

**Pull request closed without merging**
